<?php

/**
 * @file
 * Primary module hooks for slac_yaml_content module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function slac_yaml_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.slac_yaml_content':
      return t('
        <p>This module is intended for installation of default content upon initial install.  It can be disabled after initial installation.</p>
      ');
  }
}

