field.formatter.settings.view_mode_select_by_token_rendered_with_select:
  type: mapping
  label: 'Rendered With Select'
  mapping:
    view_mode:
      type: string
      label: 'View Mode'
    link:
      type: boolean
      label: 'Link label to the referenced entity'
