_core:
  default_config_hash: EENsVx8JYDmz1Vsf7oRgpbenOH3I5XbY23kjUBkW1gc
saml_attribute: eduPersonEntitlement
use_workgroup_api: false
hide_local_login: true
workgroup_api_cert: ''
workgroup_api_key: ''
restriction: all
allowed:
  affiliations: {  }
  groups: {  }
  users: {  }
