name: 'Config Export Profile'
type: module
description: 'Updates a install profile on drush cex'
core: 8.x
core_version_requirement: ^8 || ^9
package: 'Config'
configure: config_profile.settings
dependencies:
  - config_filter:config_filter
  - drupal:config


# Information added by Drupal.org packaging script on 2021-02-04
version: '8.x-1.0'
project: 'config_profile'
datestamp: 1612424972
