# Design Tokens
# Define basic design variables here.
gesso:
  palette:
    brand:
      cardinal:
        base: '#8c1515'
        light: '#b83a4b'
        dark: '#820000'
      digital-red:
        base: '#b1040e'
        light: '#e50808'
      lagunita:
        base: '#007c92'
        light: '#1aa4bc'
        dark: '#006983'
      sky:
        base: '#4298b5'
        slac: '#0099cc'
        light: '#67afd2'
        dark: '#016895'
      stormy:
        dark: '#013948'
      palo-verde:
        base: '#279989'
        light: '#59b3a9'
        dark: '#017e7c'
      palo-alto:
        base: '#175e54'
        light: '#2d716f'
        dark: '#014240'
      teal:
        base: '#00505c'
      bay:
        base: '#6fa287'
        light: '#8ab8a7'
        light-1: '#c9ded6'
        dark: '#4a7865'
      sage:
        light: '#c7d1c5'
      lime:
        base: '#8bc751'
      illuminating:
        base: '#fedd5c'
        light: '#ffe781'
        dark: '#fec51d'
      poppy:
        base: '#e98300'
        light: '#f9a44a'
        dark: '#d1660f'
      spirited:
        base: '#e04f39'
        light: '#f4795b'
        dark: '#c74632'
      stone:
        base: '#928b81'
        light: '#d4d1d1'
        dark: '#544948'
      clay:
        base: '#5f574f'
      fog:
        base: '#dad7cb'
        light: '#f4f4f4'
        dark: '#b6b1a9'
      purple:
        base: '#53284f'
        light: '#665264'
        dark: '#3d1e3a'
      lavender:
        base: '#765e99'
    grayscale:
      white: '#ffffff'
      gray-1: '#eaeaea'
      gray-2: '#d5d5d4'
      gray-3: '#c0c0bf'
      gray-4: '#ababa9'
      gray-5: '#979694'
      gray-6: '#767674'
      gray-7: '#6d6c69'
      gray-8: '#585754'
      gray-9: '#43423e'
      cool-gray: '#53565a'
      stanford-black: '#2e2d29'
      black: '#000000'
  box-shadow:
    0: none
    1: 5px 5px 20px rgba(0, 0, 0, 0.1);
    2: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23)
    3: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23)
    4: 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22)
    5: 0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22)
  constrains:
    sm: 600px
    images: 812px
    teaser: 1026px
    md: 1304px
    lg: 2200px
  breakpoints:
    mobile: 320px
    mobile-lg: 480px
    tablet: 640px
    tablet-lg: 880px
    desktop: 1024px
    mobile-menu: 1099px
    desktop-lg: 1280px
    widescreen: 1400px
    grid-2col: 600px
  colors:
    text:
      primary: grayscale.stanford-black
      secondary: grayscale.gray-6
      on-light: grayscale.stanford-black
      on-dark: grayscale.white
      link: grayscale.stanford-black
      link-hover: brand.digital-red.base
      link-active: brand.digital-red.base
      link-visited: grayscale.stanford-black
      link-underline: grayscale.stanford-black
    background:
      site: grayscale.white
      subfooter: brand.cardinal.base
      dropdown-menu: grayscale.white
    button:
      primary:
        background: grayscale.black
        background-hover: grayscale.white
        background-active: grayscale.white
        border: grayscale.black
        border-hover: grayscale.black
        text: grayscale.white
        text-hover: grayscale.black
        text-active: grayscale.black
      secondary:
        background: grayscale.white
        background-hover: 'transparent'
        background-active: 'transparent'
        border: grayscale.white
        border-hover: grayscale.white
        text: grayscale.black
        text-hover: grayscale.white
        text-active: grayscale.white
      base:
        background: grayscale.black
        background-hover: grayscale.white
        background-active: grayscale.white
        border: grayscale.black
        border-hover: grayscale.black
        text: grayscale.white
        text-hover: grayscale.black
        text-active: grayscale.black
      disabled:
        background: grayscale.gray-1
        border: grayscale.gray-1
        text: grayscale.gray-3
      danger:
        background: brand.digital-red.light
        background-hover: brand.digital-red.base
        background-active: brand.digital-red.base
        border: brand.digital-red.base
        border-hover: brand.digital-red.base
        text: grayscale.white
        text-hover: grayscale.white
        text-active: grayscale.white
      back-to-top:
        background: grayscale.stanford-black
        background-hover: grayscale.black
        color: grayscale.white
        color-hover: grayscale.white
    form:
      background: grayscale.white
      background-active: grayscale.white
      background-checked: grayscale.black
      background-unchecked: grayscale.white
      border: grayscale.gray-2
      border-dark: grayscale.gray-5
      border-light: grayscale.gray-1
      thumb: grayscale.gray-5
      track: grayscale.gray-3
    mark:
      background: brand.illuminating.base
      text: grayscale.gray-7
    selection:
      background: grayscale.stanford-black
      text: grayscale.white
    table:
      border: grayscale.gray-5
      background: grayscale.white
      background-head: grayscale.gray-1
      background-foot: grayscale.gray-1
    ui:
      generic:
        background: grayscale.gray-3
        background-darker: grayscale.stanford-black
        background-dark: grayscale.gray-6
        background-light: grayscale.gray-1
        background-lighter: grayscale.gray-1
        border: grayscale.gray-3
        border-dark: grayscale.gray-6
        border-light: brand.sky.base
        text-lighter: grayscale.white
        text-light: grayscale.gray-3
        text-dark: grayscale.gray-5
        text-darker: grayscale.gray-7
        accent: brand.cardinal.base
        accent-dark: brand.stormy.dark
        accent-light: brand.digital-red.base
        focus: brand.lagunita.light
      error:
        background: brand.digital-red.light
        border: brand.digital-red.base
      success:
        background: brand.bay.light-1
        border: brand.bay.dark
      warning:
        background: brand.illuminating.light
        border: brand.illuminating.dark
  typography:
    font-family:
      primary:
        name: Primary
        stack: '"Lato", Arial, sans-serif'
      secondary:
        name: Secondary
        stack: '"Merriweather", Georgia, serif'
      system:
        name: System
        stack: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Oxygen-Sans", Ubuntu, Cantarell, "Fira Sans", Droid Sans, sans-serif'
      monospace:
        name: Monospace
        stack: 'Menlo, Consolas, "Lucida Console", "Liberation Mono", "Courier New", monospace, sans-serif'
    base-font-size: 16px
    font-size:
      1: 14px
      2: 16px
      3: 18px
      4: 22px
      5: 26px
      6: 30px
      7: 38px
      8: 40px
      9: 42px
      10: 50px
      11: 62px
    responsive-font-size-min-width: 360px
    responsive-font-size-max-width: 1400px
    responsive-font-size:
      1:
        min: 14px
        val: auto
        max: 14px
      2:
        min: 16px
        val: auto
        max: 16px
      3:
        min: 16px
        val: auto
        max: 18px
      4:
        min: 20px
        val: auto
        max: 24px
      5:
        min: 22px
        val: auto
        max: 26px
      6:
        min: 26px
        val: auto
        max: 30px
      7:
        min: 30px
        val: auto
        max: 38px
      8:
        min: 34px
        val: auto
        max: 40px
      9:
        min: 18px
        val: auto
        max: 42px
      10:
        min: 28px
        val: auto
        max: 42px
      11:
        min: 26px
        val: auto
        max: 42px
      12:
        min: 42px
        val: auto
        max: 48px
      13:
        min: 42px
        val: auto
        max: 50px
      14:
        min: 50px
        val: auto
        max: 62px
    font-weight:
      light: 300
      regular: 400
      semibold: 500
      bold: 700
      black: 900
    line-height:
      tight: 1.2
      base: 1.4
      loose: 1.8
    display:
      display:
        font-family: primary.stack
        font-weight: black
        line-height: tight
        responsive-font-size: 12
      h1:
        font-family: primary.stack
        font-feature-settings: "'liga' off"
        font-weight: black
        line-height: base
        responsive-font-size: 11
      h2:
        font-family: primary.stack
        font-feature-settings: "'liga' off"
        font-weight: bold
        line-height: base
        responsive-font-size: 6
      h3:
        font-family: primary.stack
        font-feature-settings: "'liga' off"
        font-weight: bold
        line-height: base
        responsive-font-size: 5
      h4:
        font-family: primary.stack
        font-feature-settings: "'liga' off"
        font-weight: bold
        line-height: base
        responsive-font-size: 4
      h5:
        font-family: primary.stack
        font-feature-settings: "'liga' off"
        font-weight: bold
        line-height: tight
        responsive-font-size: 3
      h6:
        font-family: primary.stack
        font-feature-settings: "'liga' off"
        font-weight: bold
        line-height: base
        responsive-font-size: 2
      blockquote:
        font-family: secondary.stack
        font-feature-settings: "'pnum' on, 'lnum' on"
        font-weight: bold
        line-height: base
        responsive-font-size: 5
      body:
        font-family: secondary.stack
        font-feature-settings: "'pnum' on, 'lnum' on"
        font-weight: regular
        line-height: loose
        responsive-font-size: 3
      body-large:
        font-family: primary.stack
        font-feature-settings: "'liga' off"
        font-weight: regular
        line-height: loose
        responsive-font-size: 4
      body-small:
        font-family: primary.stack
        font-feature-settings: "'liga' off"
        font-weight: regular
        line-height: loose
        responsive-font-size: 2
      cite:
        font-family: primary.stack
        font-feature-settings: "'liga' off"
        font-size: 3
        font-style: normal
        font-weight: regular
        line-height: base
  transitions:
    ease:
      ease-in-out: 'cubic-bezier(0.4, 0, 0.2, 1)'
      ease-out: 'cubic-bezier(0.0, 0, 0.2, 1)'
      ease-in: 'cubic-bezier(0.4, 0, 1, 1)'
      sharp: 'cubic-bezier(0.4, 0, 0.6, 1)'
    duration:
      shortest: 150ms
      short: 200ms
      standard: 375ms
      long: 400ms
      intro: 270ms
      outro: 195ms
  z-index:
    social-share: 2
    toc: 2
    back-to-top: 5
    nav: 500
    drawer: 501
    modal: 1300
  spacing:
    0: 0
    0.5: 4px
    1: 8px
    1.5: 12px
    2: 16px
    2.5: 20px
    3: 24px
    4: 32px
    4.5: 36px
    5: 40px
    6: 48px
    7: 56px
    8: 64px
    9: 72px
    10: 80px
    12: 96px
    15: 120px
  gutter-width: 40px
  site-margins:
    'mobile': 16px
    'desktop': 32px
